### ISSUE TITLE
$ is not a function

### ISSUE THREAD

**Issue by gongph** [onury/docma#16] opened 2017-05-08 10:53 UTC
command line `docma -c docma.config.json`  there is a error: 
```
$ is not a function
```

**Comment by onury** [comment] 2017-05-08 19:51
That's not related to CLI. 
Do you get this error in browser? It seems jQuery is not found.

**Comment by gongph** [comment] 2017-05-09 01:49
in win sys `cmd` command line .

**Comment by onury** [comment] 2017-05-09 02:04
Pls provide the info below:
- Docma version, (global or local?)
- Build configuration

**Comment by gongph** [comment] 2017-05-09 02:12
- env:
  - win7
  - docma@1.5.1
  - node@6.8.1
  - npm@3.10.8

- step1
```
npm i docma -g
```
- step2
```js
docma -v // Error: Source path(s) is not defined or invalid.
```

**Comment by onury** [comment] 2017-05-09 14:33
`-v` options is for verbose logs. If you don't define any source, it throws.
Use `--version` or `-V` for Docma version. 

I cannot reproduce this error you get.
Pls also provide your Docma build configuration (docma.config.json)
or a sample project if you can, which is better.

**Comment by onury** [comment] 2017-06-27 12:37
closing this. re-open if necessary.

**Closed by onury** 2017-06-27 12:37 UTC
Labels: cannot reproduce, waiting on user

**Comment by cpetry** [comment] 2017-07-23 11:22
Hi there,

just tried using docma. 
Installed it with npm but creating documentation throws the same error:
> $ is not a function
`docma -V    // 1.5.1`

I am working on win10

**Comment by onury** [comment] 2017-07-31 15:17
Pls provide your build config and sample code if possible.
Otherwise I cannot reproduce this problem.

**Comment by onury** [comment] 2017-08-17 20:28
I'm about to release v2.0.0. 

Tested the issue you've reported with both current (v1.5.1) and v2.0.0 thoroughly on Win10. Still cannot reproduce this. Both programmatic API and CLI work as expected.

@gongph, @cpetry If you can provide your complete docma.config.json and some (sample) code to document; I'll give it one more try and fix if necessary, before this release. Let me know.

**Comment by cpetry** [comment] 2017-08-18 06:59
Sorry but I already switched to pure JSDOC.
Works great for me.

**Comment by warpdesign** [comment] 2017-12-08 14:22
I am having the same error, on Windows 10 too, that's with docma `1.5.1`.

Full log:

```
docma -c ./docma.json


Building documentation...

Using Template: Docma Default Template (version: 1.7.0)

Expanding source files...
Expanding: ./js/**/*.js into "API"
Parsing 49 Javascript file(s)...
Copying template files/directories...
Compiling SPA styles...
Compiling SPA scripts...
Writing SPA main file...
$ is not a function
```

**Comment by warpdesign** [comment] 2017-12-08 14:45
It'as crashing here:

`docma.template.js`:

```js
                    .edit(function (window) {
                        $this.$debug.info(window.$, window);
                        var $ = window.$,
                            head = $('head'),
```

window.$ is not defined.

**Comment by warpdesign** [comment] 2017-12-08 15:09
jQuery's path seem to be fine:

>C:\\Users\\Nicolas\\AppData\\Roaming\\npm\\node_modules\\docma\\lib\\web\\components\\jquery.min.js

But for some reason, jsdom fails to load it.

I tried replacing it with some hardcoded url in html-parser.js and it fixes the problem.

**Comment by warpdesign** [comment] 2017-12-08 15:43
@onury I submited a pull_request that adresses this bug.
